# Generated by Django 3.2.9 on 2024-03-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='procedure',
            field=models.JSONField(default=list),
        ),
    ]
