# Generated by Django 4.2.9 on 2024-02-21 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_userprofile_allergies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='carbohydrate_content',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='fat_content',
            new_name='protein',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='protein_content',
            new_name='sodium',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
    ]
