# Generated by Django 4.2.9 on 2024-02-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_description_recipe_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(),
        ),
    ]
